plugins {
    id 'java'
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'Main'
}

repositories {
    mavenCentral()
}

jar {
    manifest {
        attributes 'Main-Class': 'Main'
    }
}
